"use client";
import {useCallback,useEffect,useState} from "react";
import {Activity,AlertTriangle,ArrowDownRight,ArrowUpRight,Clock,RefreshCw,ShieldCheck,Target,Wallet} from "lucide-react";
import type {Backtest,State} from "@/lib/types";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
const price=(n?:number)=>n?.toFixed(5)||"—";

export function Dashboard(){
 const [data,setData]=useState<State|null>(null);const [backtest,setBacktest]=useState<Backtest|null>(null);const [loading,setLoading]=useState(true);const [backtesting,setBacktesting]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch(`${API}/api/state`,{cache:"no-store"});if(!r.ok)throw new Error(`API request failed (${r.status})`);setData(await r.json());setError("")}catch(e){setError(e instanceof TypeError?`Cannot reach the API at ${API}`:e instanceof Error?e.message:"Connection failed")}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[load]);
 async function scan(){setLoading(true);try{const r=await fetch(`${API}/api/scan`,{method:"POST"});if(!r.ok){const x=await r.json();throw new Error(x.detail||"Scan failed")}await load()}catch(e){setError(e instanceof Error?e.message:"Scan failed")}finally{setLoading(false)}}
 async function runBacktest(){setBacktesting(true);try{const r=await fetch(`${API}/api/backtest`,{method:"POST"});if(!r.ok){const x=await r.json();throw new Error(x.detail||"Backtest failed")}setBacktest(await r.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Backtest failed")}finally{setBacktesting(false)}}
 const sig=data?.latest_signal;const trade=data?.open_trade;
 return <main><header><div><span className="logoPulse"/><strong>EUR/USD</strong><small>{data?.interval||"—"} paper trader</small></div><div className="headerRight"><span className="demo"><ShieldCheck size={15}/> PAPER ONLY</span><span className="feed"><span/> {data?.feed||"offline"}</span><span className={`feed ${data?.news?.blocking?"red":""}`}>NEWS {data?.news?.status||"—"}</span><button onClick={runBacktest} disabled={backtesting}><Activity size={16} className={backtesting?"spin":""}/> {backtesting?"Testing…":"Backtest"}</button><button onClick={scan} disabled={loading}><RefreshCw size={16} className={loading?"spin":""}/> Scan now</button></div></header>
 <section className="wrap"><div className="hero"><div><p className="overline">AUTOMATED MARKET MONITOR</p><h1>EUR/USD <span>{data?.interval||"—"}</span></h1><p>The engine evaluates every newly closed candle and opens only simulated trades when EMA trend, MACD, RSI and momentum agree.</p></div><div className={`signal ${sig?.action?.toLowerCase()||"hold"}`}><small>LATEST SIGNAL</small><strong>{sig?.action||"WAITING"}</strong><span>{sig?`${Math.round(sig.confidence*100)}% confirmation`:"Starting engine…"}</span></div></div>
 {error&&<div className="error"><AlertTriangle/> <div><strong>Connection or data error</strong><p>{error}. Make sure FastAPI is running and the Twelve Data key is configured.</p></div></div>}
 <div className="metrics"><Metric icon={<Wallet/>} label="Balance" value={data?money(data.account.balance):"—"} sub="Starting balance $10,000"/><Metric icon={<Activity/>} label="Equity" value={data?money(data.account.equity):"—"} sub="Includes floating paper P/L"/><Metric icon={<Target/>} label="Win rate" value={data?`${data.stats.win_rate}%`:"—"} sub={`${data?.stats.closed||0} closed demo trades`}/><Metric icon={<Clock/>} label="Last candle" value={sig?new Date(sig.candle_time).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"—"} sub={sig?new Date(sig.candle_time).toLocaleDateString():"Waiting for market data"}/></div>
 <div className="grid"><section className="panel"><div className="panelHead"><div><small>CURRENT ANALYSIS</small><h2>{price(sig?.price)}</h2></div><span className="symbol">EUR / USD</span></div>{sig?<><p className="reason">{sig.reason}</p><div className="indicators"><Indicator label="EMA 20" value={price(sig.indicators.ema20)}/><Indicator label="EMA 50" value={price(sig.indicators.ema50)}/><Indicator label="RSI 14" value={sig.indicators.rsi.toFixed(1)}/><Indicator label="ATR 14" value={price(sig.indicators.atr)}/><Indicator label="MACD" value={sig.indicators.macd.toFixed(6)}/><Indicator label="Momentum 10" value={`${(sig.indicators.momentum_10*100).toFixed(3)}%`}/></div></>:<p className="empty">Waiting for the first scan.</p>}</section>
 <section className="panel"><div className="panelHead"><div><small>OPEN POSITION</small><h2>{trade?`${trade.side} #${trade.id}`:"No trade"}</h2></div>{trade&&(trade.side==="BUY"?<ArrowUpRight className="green"/>:<ArrowDownRight className="red"/>)}</div>{trade?<div className="position"><div><small>Entry</small><b>{price(trade.entry)}</b></div><div><small>Stop loss</small><b className="red">{price(trade.stop_loss)}</b></div><div><small>Take profit</small><b className="green">{price(trade.take_profit)}</b></div><div><small>Risk</small><b>{money(trade.risk_amount)}</b></div><div><small>Demo units</small><b>{trade.units.toLocaleString()}</b></div><div><small>Opened</small><b>{new Date(trade.opened_at).toLocaleString()}</b></div></div>:<div className="emptyState"><ShieldCheck/><h3>Waiting for full confirmation</h3><p>Only one paper position can be open at a time.</p></div>}</section></div>
 <section className="panel history"><div className="panelHead"><div><small>PAPER JOURNAL</small><h2>Recent trades</h2></div></div><div className="table"><div className="tr row"><b>Trade</b><b>Entry</b><b>Stop / Target</b><b>Status</b><b>P/L</b></div>{data?.trades.length?data.trades.map(t=><div className="row" key={t.id}><span><b className={t.side==="BUY"?"green":"red"}>{t.side}</b><small> #{t.id}</small></span><span>{price(t.entry)}</span><span>{price(t.stop_loss)} / {price(t.take_profit)}</span><span className="status">{t.status}</span><b className={t.pnl>0?"green":t.pnl<0?"red":""}>{money(t.pnl||0)}</b></div>):<p className="empty">No paper trades yet.</p>}</div></section>
 {backtest&&<section className="panel backtest"><div className="panelHead"><div><small>HISTORICAL BACKTEST</small><h2>{backtest.bars} candles · {backtest.feed}</h2></div><span className="symbol">Costs: {backtest.assumptions.spread_pips} pip spread + {backtest.assumptions.slippage_pips} pip slippage</span></div><p className="reason">Historical simulation only. It uses the same higher-timeframe entry gate as paper trading, 1% risk sizing, and conservative same-candle stop handling.</p><div className="indicators"><Indicator label="Net P/L" value={money(backtest.metrics.net_pnl)}/><Indicator label="Return" value={`${backtest.metrics.return_percent}%`}/><Indicator label="Max drawdown" value={`${backtest.metrics.max_drawdown_percent}%`}/><Indicator label="Closed trades" value={String(backtest.metrics.closed_trades)}/><Indicator label="Win rate" value={`${backtest.metrics.win_rate}%`}/><Indicator label="Profit factor" value={backtest.metrics.profit_factor?.toFixed(2)||"—"}/></div><div className="indicators"><Indicator label="Expectancy / trade" value={money(backtest.diagnostics.overall.expectancy_per_trade)}/><Indicator label="Break-even win rate" value={backtest.diagnostics.overall.breakeven_win_rate===null?"—":`${backtest.diagnostics.overall.breakeven_win_rate}%`}/><Indicator label="Max loss streak" value={String(backtest.diagnostics.max_consecutive_losses)}/><Indicator label="BUY P/L" value={money(backtest.diagnostics.by_side.BUY.net_pnl)}/><Indicator label="SELL P/L" value={money(backtest.diagnostics.by_side.SELL.net_pnl)}/><Indicator label="HTF filter" value={backtest.assumptions.higher_timeframe_filter?"Applied":"Off"}/></div></section>}
 <footer><ShieldCheck size={16}/> Demo execution only. No broker connection and no real-money order endpoint.</footer></section></main>}
function Metric({icon,label,value,sub}:{icon:React.ReactNode;label:string;value:string;sub:string}){return <div className="metric"><span className="metricIcon">{icon}</span><small>{label}</small><strong>{value}</strong><p>{sub}</p></div>}
function Indicator({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
